-- Cria tabela para registrar visitas por novel/título
-- Rode no Supabase SQL Editor antes de publicar a API

create table if not exists public.visitas (
  id bigint generated by default as identity primary key,
  data timestamptz not null default now(),
  title text not null,
  novel text not null,
  tags text[] not null default '{}'::text[]
);

-- Se a tabela já existir sem a coluna, adiciona tags
alter table public.visitas
  add column if not exists tags text[] not null default '{}'::text[];

-- Índices para consultas por novel e ordenação por data
create index if not exists visitas_novel_idx on public.visitas (novel);
create index if not exists visitas_data_idx on public.visitas (data desc);
create index if not exists visitas_tags_gin on public.visitas using gin (tags);
